---

- name: Preparação do ambiente para o MongoDB
  hosts: all
  become: true
  tasks:

  - name: Baixar a imagem do MongoDB
    command:
      cmd: docker images mongo

  - name: Baixar a imagem do MongoDB Express
    command:
      cmd: docker images mongo-express
